"""
Main application entry point.

Orchestrates:
1. Historical data bootstrap
2. WebSocket server for real-time streaming
3. HTTP API server for queries
4. Live metric/event generation
"""
import asyncio
import time
import uvicorn
from multiprocessing import Process

from simulator.metrics_generator import get_generator
from simulator.event_generator import get_event_generator
from simulator.bootstrap import bootstrap_historical_data
from storage.metrics_store import get_metrics_store
from storage.events_store import get_events_store
from server.websocket_server import get_websocket_server
from server.http_api import app


async def stream_metrics_loop():
    """
    Continuously generate and broadcast metric observations.
    
    Generates all 7 metrics every 10 seconds and broadcasts via WebSocket.
    """
    generator = get_generator()
    metrics_store = get_metrics_store()
    ws_server = get_websocket_server()
    
    print("Starting metric streaming loop (10 sec interval)...")
    
    while True:
        try:
            # Generate observation for each metric
            for metric in generator.get_all_metrics():
                observation = generator.generate_observation(metric)
                
                # Store it
                metrics_store.insert_observation(observation)
                
                # Broadcast it
                await ws_server.broadcast_metric(observation)
            
            # Advance time
            generator.tick(10)
            
            # Wait 10 seconds before next batch
            await asyncio.sleep(10)
            
        except Exception as e:
            print(f"Error in metrics loop: {e}")
            await asyncio.sleep(1)


async def stream_events_loop():
    """
    Handle event generation and broadcasting.
    
    Events are generated by the scheduler, we just register callbacks.
    """
    event_generator = get_event_generator()
    events_store = get_events_store()
    ws_server = get_websocket_server()
    
    # Register callback to handle generated events
    async def handle_event(event):
        # Store it
        events_store.insert_event(event)
        
        # Broadcast it
        await ws_server.broadcast_event(event)
    
    # Wrap sync callback for async scheduler
    def sync_callback(event):
        asyncio.create_task(handle_event(event))
    
    event_generator.register_callback(sync_callback)
    
    # Schedule random events every 5 minutes
    event_generator.schedule_random_events(interval_minutes=5)
    
    # Start scheduler
    event_generator.start()
    
    print("Event generator started (random events every 5 min)")


async def run_backend():
    """
    Run the complete backend system.
    
    1. Bootstrap historical data
    2. Start WebSocket server
    3. Start metric streaming
    4. Start event streaming
    """
    print("\n" + "="*60)
    print("Network Monitoring Backend")
    print("="*60 + "\n")
    
    # Clear and regenerate historical data on each startup
    # This ensures timestamps are always current for the prototype
    print("Clearing existing data...")
    metrics_store = get_metrics_store()
    events_store = get_events_store()
    
    # Clear all data
    for metric in ["time_to_connect", "throughput", "coverage", "capacity", 
                   "roaming", "successful_connects", "ap_health"]:
        metrics_store.delete_all(metric)
    events_store.delete_all()
    
    # Bootstrap with 90 days of tiered historical data
    bootstrap_historical_data(days=90)
    
    # Start WebSocket server
    ws_server = get_websocket_server(host="0.0.0.0", port=8000)
    await ws_server.start()
    
    # Start streaming loops
    await asyncio.gather(
        stream_metrics_loop(),
        stream_events_loop()
    )


def run_http_api():
    """Run FastAPI HTTP server in a separate process."""
    uvicorn.run(
        app,
        host="0.0.0.0",
        port=8001,
        log_level="info"
    )


if __name__ == "__main__":
    # Start HTTP API in separate process
    api_process = Process(target=run_http_api)
    api_process.start()
    
    print("\n" + "="*60)
    print("FastAPI HTTP server starting on http://0.0.0.0:8001")
    print("API docs available at http://localhost:8001/docs")
    print("="*60 + "\n")
    
    # Run WebSocket + streaming in main process
    try:
        asyncio.run(run_backend())
    except KeyboardInterrupt:
        print("\n\nShutting down...")
        api_process.terminate()
        api_process.join()
        print("Shutdown complete")
