"""
Main application entry point.

Orchestrates:
1. Historical data bootstrap
2. WebSocket server for real-time streaming
3. HTTP API server for queries (same process for shared storage)
4. Live metric/event generation
"""
import asyncio
import time
import uvicorn

from simulator.realistic_generator import get_generator, NETWORK_PROFILES
from simulator.event_generator import get_event_generator
from simulator.bootstrap import bootstrap_historical_data
from storage.metrics_store import get_metrics_store
from storage.events_store import get_events_store
from server.websocket_server import get_websocket_server
from server.http_api import app


async def stream_metrics_loop():
    """
    Continuously generate and broadcast metric observations.
    
    Generates all 7 metrics every 10 seconds and broadcasts via WebSocket.
    Uses real wall clock time for live observations.
    """
    generator = get_generator()
    metrics_store = get_metrics_store()
    ws_server = get_websocket_server()
    
    print("Starting metric streaming loop (10 sec interval)...")
    
    while True:
        try:
            # Use actual current time for live observations
            current_time = int(time.time())
            
            # Generate observation for each metric at current time
            for metric in generator.get_all_metrics():
                observation = generator.generate_observation(metric, timestamp=current_time)
                
                # Store it
                metrics_store.insert_observation(observation)
                
                # Broadcast it
                await ws_server.broadcast_metric(observation)
            
            # No need to tick() - we use actual wall clock time
            # The generator's internal state (noise, correlations) is preserved
            # but timestamps come from real time
            
            # Wait 10 seconds before next batch
            await asyncio.sleep(10)
            
        except Exception as e:
            print(f"Error in metrics loop: {e}")
            await asyncio.sleep(1)


async def stream_events_loop():
    """
    Handle event generation and broadcasting.
    
    Events are generated by the scheduler, we just register callbacks.
    """
    event_generator = get_event_generator()
    metrics_generator = get_generator()
    events_store = get_events_store()
    ws_server = get_websocket_server()

    # Wire event generator to metrics generator for perturbation causality
    event_generator.set_metrics_generator(metrics_generator)

    # Register callback to handle generated events
    async def handle_event(event):
        # Store it
        events_store.insert_event(event)
        
        # Broadcast it
        await ws_server.broadcast_event(event)
    
    # Wrap sync callback for async scheduler
    def sync_callback(event):
        asyncio.create_task(handle_event(event))
    
    event_generator.register_callback(sync_callback)
    
    # Schedule random events every 5 minutes
    event_generator.schedule_random_events(avg_interval_minutes=5)
    
    # Start scheduler
    event_generator.start()
    
    print("Event generator started (random events every 5 min)")


async def cleanup_old_data_loop():
    """
    Delete data older than 30 days to maintain rolling window.
    
    Runs once per day at 3:00 AM to minimize impact on performance.
    For continuous operation, this keeps storage bounded while avoiding
    frequent expensive delete operations on CSV storage.
    """
    from datetime import datetime, timedelta
    
    metrics_store = get_metrics_store()
    events_store = get_events_store()
    
    # Retention period: 30 days
    retention_seconds = 30 * 24 * 3600
    
    print(f"Data cleanup task started (runs daily at 3:00 AM, keeps {retention_seconds/86400:.0f} days)")
    
    while True:
        try:
            # Calculate next 3 AM
            now = datetime.now()
            next_run = now.replace(hour=3, minute=0, second=0, microsecond=0)
            
            # If it's already past 3 AM today, schedule for tomorrow
            if next_run <= now:
                next_run += timedelta(days=1)
            
            # Wait until scheduled time
            wait_seconds = (next_run - now).total_seconds()
            print(f"Next cleanup scheduled for: {next_run.strftime('%Y-%m-%d %H:%M:%S')}")
            
            await asyncio.sleep(wait_seconds)
            
            # Perform cleanup
            print(f"\nRunning daily cleanup at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}...")
            cutoff = int(time.time()) - retention_seconds
            
            metrics_deleted = metrics_store.delete_older_than(cutoff)
            events_deleted = events_store.delete_older_than(cutoff)
            
            print(f"Cleanup complete: deleted {metrics_deleted} metrics and {events_deleted} events older than {time.ctime(cutoff)}\n")
            
        except Exception as e:
            print(f"Error in cleanup loop: {e}")
            import traceback
            traceback.print_exc()
            # Wait 1 hour before retrying on error
            await asyncio.sleep(3600)


async def run_backend():
    """
    Run the complete backend system.
    
    1. Bootstrap historical data
    2. Start HTTP API server (in same process for shared storage)
    3. Start WebSocket server
    4. Start metric streaming
    5. Start event streaming
    """
    import os

    print("\n" + "="*60)
    print("Network Monitoring Backend")
    print("="*60)

    # Show available profiles
    current_profile = os.environ.get("NETWORK_PROFILE", "enterprise").lower()
    print(f"\nAvailable network profiles: {', '.join(NETWORK_PROFILES.keys())}")
    print(f"Current profile: {current_profile}")
    print("(Set NETWORK_PROFILE env var to switch, e.g.: NETWORK_PROFILE=hospital python main.py)\n")

    # Check if we should skip bootstrap (for continuous operation)
    skip_bootstrap = os.environ.get("SKIP_BOOTSTRAP", "false").lower() == "true"
    
    # Get absolute paths to database files
    from pathlib import Path
    backend_dir = Path(__file__).parent
    db_files = [
        backend_dir / "data" / "metrics.csv",
        backend_dir / "data" / "events.db"
    ]
    
    # Determine if this is first run (no data exists)
    has_existing_data = any(db_file.exists() for db_file in db_files)
    
    if skip_bootstrap and has_existing_data:
        # Continuous operation mode - keep existing data
        print("\n" + "="*60)
        print("CONTINUOUS OPERATION MODE")
        print("="*60)
        print("Existing data found and SKIP_BOOTSTRAP=true")
        print("Preserving historical data and resuming live generation")
        
        # Show age of existing data
        metrics_csv = db_files[0]
        if metrics_csv.exists():
            age_seconds = time.time() - metrics_csv.stat().st_mtime
            age_hours = age_seconds / 3600
            print(f"Data file last modified: {age_hours:.1f} hours ago")
        print("="*60 + "\n")
        
    else:
        # Fresh start - clear and regenerate
        if skip_bootstrap and not has_existing_data:
            print("\nSKIP_BOOTSTRAP=true but no existing data found")
            print("Performing initial bootstrap...\n")
        else:
            print("\nClearing existing data for fresh start...")
        
        # Delete database files entirely to ensure clean slate
        for db_file in db_files:
            if db_file.exists():
                print(f"  Deleting {db_file.name}...")
                db_file.unlink()
        
        # Reset singleton instances to get fresh database connections
        from storage.metrics_store import reset_metrics_store
        from storage.events_store import reset_events_store
        reset_metrics_store()
        reset_events_store()
        
        # Bootstrap tiered historical data ending at current time
        # Duration is determined by tier configuration (~30 days)
        bootstrap_historical_data()
        print()
    
    # Reset generator to start live streaming (preserves noise state for continuity)
    from simulator.realistic_generator import reset_for_live_streaming
    reset_for_live_streaming()
    
    # Start HTTP API server in background task (same process!)
    config = uvicorn.Config(
        app,
        host="0.0.0.0",
        port=5011,
        log_level="info"
    )
    server = uvicorn.Server(config)
    
    print("\n" + "="*60)
    print("FastAPI HTTP server starting on http://0.0.0.0:5011")
    print("API docs available at http://localhost:5011/docs")
    print("="*60 + "\n")
    
    # Start WebSocket server
    ws_server = get_websocket_server(host="0.0.0.0", port=5010)
    await ws_server.start()
    
    # Start all services in parallel
    await asyncio.gather(
        server.serve(),  # HTTP API
        stream_metrics_loop(),
        stream_events_loop(),
        cleanup_old_data_loop()  # Periodic cleanup to maintain 30-day window
    )


if __name__ == "__main__":
    # Run everything in single process so storage is shared
    try:
        asyncio.run(run_backend())
    except KeyboardInterrupt:
        print("\n\nShutting down...")
        print("Shutdown complete")
